/* dashboard/_shared/pnl.js — pure P&L math extracted from sales/index.html.
   Loaded as a classic <script src> BEFORE the inline script, so every function and
   constant here is a window global exactly as before. Depends ONLY on the global
   STATE object (defined in index.html). No DOM, no rendering. Node-testable via vm.
   Generated by build_extract.mjs — closure of the seed math functions. */

var REAL_VENUES = ['mari', 'stow', 'hg'];

var OVERHEADS_WEEKLY = { stow: 8899, hg: 2890, mari: 1779, group: 13568 };

var PLAN_WAGE_SHARE = { stow: 0.624, hg: 0.207, mari: 0.170, group: 1.0 };

function winEnd(day) {
  const t = String(day.date || '');
  if (t.includes(' \u2014 ')) return t.split(' \u2014 ')[1];
  return /^\d{4}-\d{2}-\d{2}$/.test(t) ? t : isoDate(sydneyToday());
}

function yoyRevenueDelta(rows, timeframe, anchorDay) {
  const cur = rowsForTimeframe(rows, timeframe, anchorDay);
  if (!cur.length) return null;
  const ps = isoDate(addDays(new Date(cur[0].date), -364));
  const pe = isoDate(addDays(new Date(cur[cur.length - 1].date), -364));
  const prev = rows.filter(r => r.date >= ps && r.date <= pe);
  if (!prev.length || prev.length < cur.length * 0.8) return null;
  const cr = cur.reduce((t, r) => t + toNum(r.revenue_ex_gst), 0);
  const pr = prev.reduce((t, r) => t + toNum(r.revenue_ex_gst), 0);
  if (!pr) return null;
  return (cr - pr) / pr * 100;
}

/* Week-on-week revenue. Day view: this day vs the SAME weekday over recent weeks
   (a Saturday vs recent Saturdays). Week view: this week vs recent weeks. Shifts
   the CURRENT window back in 7-day steps (weekday-aligned so partial weeks compare
   like-for-like at the same point), and averages up to 4 prior weeks with
   comparable coverage. Returns null unless >=2 usable comparators. Day/week only. */
function wowRevenueDelta(rows, timeframe, anchorDay) {
  if (timeframe !== 'day' && timeframe !== 'week' && timeframe !== 'lastweek') return null;
  const cur = rowsForTimeframe(rows, timeframe, anchorDay);
  if (!cur.length) return null;
  const curRev = cur.reduce((t, r) => t + toNum(r.revenue_ex_gst), 0);
  if (!curRev) return null;
  const s0 = new Date(cur[0].date), e0 = new Date(cur[cur.length - 1].date);
  const prev = [];
  for (let n = 1; n <= 4; n++) {
    const ps = isoDate(addDays(s0, -7 * n)), pe = isoDate(addDays(e0, -7 * n));
    const wk = rows.filter(r => r.date >= ps && r.date <= pe);
    if (wk.length >= Math.max(1, cur.length * 0.8)) prev.push(wk.reduce((t, r) => t + toNum(r.revenue_ex_gst), 0));
  }
  if (prev.length < 2) return null;
  const avg = prev.reduce((a, b) => a + b, 0) / prev.length;
  if (!avg) return null;
  return { delta: (curRev - avg) / avg * 100, nWeeks: prev.length, avg, curRev,
           weekday: timeframe === 'day' ? new Date(cur[0].date).toLocaleDateString('en-AU', { weekday: 'long' }) : null };
}

/* Series for the Week-on-Week section. Day view -> the SAME weekday over the last
   n weeks (last n Saturdays); every other view -> full Mon-Sun weeks. Newest first.
   Each entry carries the full P&L KPI set from pnlWindow, so the table/chart match
   the rest of the dashboard exactly (wages excl driver, delivery incl driver). */

function wowSeries(venue, timeframe, anchorDay, nWeeks) {
  const rows = STATE.histories[venue] || [];
  if (!rows.length || !anchorDay) return [];
  const weekday = timeframe === 'day';
  const histMin = rows[0].date, histMax = rows[rows.length - 1].date;
  const anchor = new Date(anchorDay);
  // Recent ACTUAL COGS% (Xero) — used as a stable estimate for weeks too old to
  // have booked COGS, where the POS-theoretical figure is missing/unreliable.
  const actRate = (actualCogs(venue, histMax, 12) || {}).pct || null;
  const out = [];
  for (let n = 0; n < nWeeks; n++) {
    let sIso, eIso, label;
    if (weekday) {
      const d = addDays(anchor, -7 * n);
      sIso = eIso = isoDate(d);
      label = d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' });
    } else {
      const ws = addDays(weekStart(anchor), -7 * n);
      sIso = isoDate(ws); eIso = isoDate(addDays(ws, 6));
      label = 'w/c ' + ws.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' });
    }
    if (eIso < histMin) break;
    const sub = rows.filter(r => r.date >= sIso && r.date <= eIso);
    if (!sub.length) continue;
    const w = pnlWindow(rollup(sub), venue);
    if (!w) continue;
    // COGS: real Xero weekly actual where we have it; otherwise scale the POS
    // theoretical up to actual level (flagged est).
    const estCogs = !actualCogs(venue, eIso);
    const cogsPct = estCogs && actRate ? actRate : w.cogsPct;
    const cogs = w.rev * cogsPct / 100;
    // Delivery is an estimate whenever it isn't booked WEEKLY Uber data (i.e. it
    // came from the monthly Xero rate or the blended fallback) — flag those.
    const estDelivery = (venue === 'mari' || venue === 'group')
      ? !venueDeliveryEst('mari', sIso, eIso, eIso).actual : false;
    // Profit recomputed for the (possibly scaled) COGS; everything else unchanged.
    const profit = w.profit - (cogs - w.rev * w.cogsPct / 100);
    out.push({ label, s: sIso, e: eIso, partial: eIso > histMax,
      est: estCogs || estDelivery, estCogs, estDelivery,
      rev: w.rev, cogsPct,
      wagesPct: w.rev ? w.wages / w.rev * 100 : 0,
      delivPct: w.rev ? w.df / w.rev * 100 : 0,
      profit, margin: w.rev ? profit / w.rev * 100 : 0,
      cogs, wages: w.wages, df: w.df, cp: w.cp, oh: w.oh });
  }
  return out;
}

function wageMedian12wk(rows) {
  const byWk = {};
  for (const r of rows) {
    if (!hasVal(r.wages_dollars)) continue;
    const ws = isoDate(weekStart(new Date(r.date)));
    const b = byWk[ws] = byWk[ws] || { w: 0, rev: 0 };
    b.w += toNum(r.wages_dollars); b.rev += toNum(r.revenue_ex_gst);
  }
  const wks = Object.keys(byWk).sort().slice(-13, -1);
  const pcts = wks.map(k => byWk[k].rev ? byWk[k].w / byWk[k].rev * 100 : null)
                  .filter(x => x !== null).sort((a, b) => a - b);
  return pcts.length ? pcts[Math.floor(pcts.length / 2)] : null;
}

function corpPayrollDaily(venue, endIso) {
  const wk = STATE.oncost.ownerWeekly || 0;
  return wk * (PLAN_WAGE_SHARE[venue] || 0) / 7;
}

function wageOncostDaily(venue, endIso) {
  const feed = STATE.xeroOH;
  if (!feed.length) return 0;
  const endMonth = String(endIso || '').slice(0, 7);
  const months = feed.filter(r => r.month && r.month < endMonth && hasVal(r.group_payroll))
                     .sort((a, b) => a.month.localeCompare(b.month)).slice(-3);
  if (!months.length) return 0;
  const monthSet = new Set(months.map(r => r.month));
  let gp = 0, days = 0;
  for (const r of months) {
    gp += toNum(r.group_payroll);
    const [y, m] = r.month.split('-').map(Number);
    days += new Date(y, m, 0).getDate();
  }
  let deputy = 0;
  for (const v of REAL_VENUES) for (const r of (STATE.histories[v] || [])) {
    if (monthSet.has(r.date.slice(0, 7))) deputy += toNum(r.wages_dollars) + toNum(r.leave_dollars);
  }
  const ownerTot = (STATE.oncost.ownerWeekly || 0) / 7 * days;   // owners over same days
  const oncost = Math.max(0, gp - deputy - ownerTot);            // payroll tax + WC (+ timing)
  return days ? oncost * (PLAN_WAGE_SHARE[venue] || 0) / days : 0;
}

function dowShares(venue) {
  STATE._dow = STATE._dow || {};
  if (STATE._dow[venue] !== undefined) return STATE._dow[venue];
  const rows = (STATE.histories[venue] || []).slice(-84);
  const sum = [0,0,0,0,0,0,0], cnt = [0,0,0,0,0,0,0];
  for (const r of rows) {
    const rev = toNum(r.revenue_ex_gst);
    if (!rev) continue;
    const d = new Date(r.date).getDay();
    sum[d] += rev; cnt[d]++;
  }
  const means = sum.map((x, i) => cnt[i] ? x / cnt[i] : 0);
  const tot = means.reduce((a, b) => a + b, 0);
  STATE._dow[venue] = tot ? means.map(x => x / tot) : null;
  return STATE._dow[venue];
}

function ohFactor(day, venue, wdays) {
  const shares = dowShares(venue);
  if (!shares) return wdays;
  if (day.dow_counts) return 7 * day.dow_counts.reduce((t, c, i) => t + c * shares[i], 0);
  const t = String(day.date || '');
  if (/^\d{4}-\d{2}-\d{2}$/.test(t)) return 7 * shares[new Date(t).getDay()];
  return wdays;
}

function uberRateFallback(venue) {
  // Blended Uber-fee rate (inc GST) as a share of revenue, from the weeks we DO
  // have Uber actuals for. Used to ESTIMATE delivery on older weeks that predate
  // the Uber feed, so a delivery brand's cost line isn't left at driver-only.
  if (venue !== 'mari' || !STATE.uberFees || !STATE.uberFees.length) return null;
  const hist = STATE.histories.mari || [];
  let fees = 0, rev = 0;
  for (const r of STATE.uberFees) {
    if (r.venue !== 'mari' || !r.week_ending) continue;
    fees += toNum(r.total_fees_inc_gst);
    const s0 = isoDate(addDays(new Date(r.week_ending), -6));
    for (const d of hist) if (d.date >= s0 && d.date <= r.week_ending) rev += toNum(d.revenue_ex_gst);
  }
  return rev ? fees / rev : null;
}

function uberWeeklyFees(venue, sIso, eIso) {
  // Weekly Uber actuals (uber_fees_weekly) — the bridge between the daily feed
  // (recent only) and the monthly Xero rate. Same inc-GST basis + shape as
  // uberSplit, so venueDeliveryEst can use it interchangeably. Prorated by the
  // overlap of each Uber week (ending week_ending) with the requested window.
  if (!STATE.uberFees || !STATE.uberFees.length) return null;
  if (venue !== 'mari' && venue !== 'hg') return null;
  let comm = 0, mkt = 0, have = false;
  for (const r of STATE.uberFees) {
    if (r.venue !== venue || !r.week_ending) continue;
    const wkStart = isoDate(addDays(new Date(r.week_ending), -6));
    const ovStart = wkStart > sIso ? wkStart : sIso;
    const ovEnd = r.week_ending < eIso ? r.week_ending : eIso;
    const days = (new Date(ovEnd) - new Date(ovStart)) / 86400000 + 1;
    if (days > 0) { const frac = days / 7; comm += toNum(r.service_fees_inc_gst) * frac; mkt += toNum(r.marketing_inc_gst) * frac; have = true; }
  }
  return have ? { commission: comm, marketing: mkt } : null;
}

function uberSplit(venue, sIso, eIso) {
  if (!STATE.uberDaily.length) return null;
  if (venue !== 'mari' && venue !== 'hg') return null;
  let comm = 0, offers = 0, have = false;
  for (const r of STATE.uberDaily) {
    if (r.shop === venue && r.date >= sIso && r.date <= eIso) {
      comm += toNum(r.commission_inc_gst); offers += toNum(r.offers_inc_gst); have = true;
    }
  }
  if (!have) return null;
  // offers_inc_gst is the portal's own "Marketing" line, which ALREADY contains
  // Uber Ads click spend as well as funded offers — Uber deducts both from the
  // payout. Adding uber_marketing_weekly (uberAds) on top double-counted ads.
  // That feed is deprecated and empty, so this was latent rather than live;
  // removed so it cannot fire if anyone ever repopulates it. (2026-08-09)
  return { commission: comm, marketing: offers };
}

function uberDailyStart(venue) {
  // First date the DAILY portal feed covers for a venue. Days before it belong
  // to the WEEKLY feed; the two are contiguous (weekly ends 2026-07-12, daily
  // starts 2026-07-13) and must never both be counted for the same day.
  let min = null;
  for (const r of (STATE.uberDaily || [])) {
    if (r.shop !== venue || !r.date) continue;
    if (min === null || r.date < min) min = r.date;
  }
  return min;
}

function uberActual(venue, sIso, eIso) {
  // Uber Eats actuals for a window, STITCHED across the two portal feeds: exact
  // per-day (uber_daily) from its first covered date onward, prorated weekly
  // (uber_fees_weekly) for the days before it.
  //
  // WHY this is not `uberSplit(...) || uberWeeklyFees(...)`: that fell through to
  // weekly only when the daily feed had NOTHING in the window. Any window that
  // straddled the boundary — "last 3 months", a quarter, June-to-August — matched
  // one daily row, took the daily branch, and silently dropped every pre-boundary
  // week. It made delivery cost too LOW, which flatters the P&L: the failure
  // direction CLAUDE.md warns about. (2026-08-09)
  const ds = uberDailyStart(venue);
  let comm = 0, mkt = 0, have = false;
  if (ds && ds <= eIso) {
    const d = uberSplit(venue, ds > sIso ? ds : sIso, eIso);
    if (d) { comm += d.commission; mkt += d.marketing; have = true; }
  }
  const wEnd = ds ? isoDate(addDays(new Date(ds), -1)) : eIso;
  if (wEnd >= sIso) {
    const w = uberWeeklyFees(venue, sIso, wEnd < eIso ? wEnd : eIso);
    if (w) { comm += w.commission; mkt += w.marketing; have = true; }
  }
  if (!have) return null;
  // How far the feed actually REACHES, so a caller can tell a complete window
  // from one whose tail has not landed. uberDirectActual and uberSvcWindow both
  // refuse partial coverage; this one is summed per-day, so instead it reports
  // the boundary and lets venueDeliveryEst estimate the remainder.
  const end = uberDailyEnd(venue);
  return { commission: comm, marketing: mkt,
           coveredEnd: end, covered: !!end && end >= eIso };
}

function uberDailyEnd(venue) {
  // Last date the DAILY feed reaches for a venue. Today is normally uncovered —
  // the pull runs next morning — so most live windows have a one-day tail.
  let max = null;
  for (const r of (STATE.uberDaily || [])) {
    if (r.shop !== venue || !r.date) continue;
    if (max === null || r.date > max) max = r.date;
  }
  return max;
}

function uberEatsShareOfDelivery(venue, endIso) {
  if (venue !== 'mari') return 0;
  const feed = STATE.xeroOH;
  const endMonth = String(endIso || '').slice(0, 7);
  const months = feed.filter(r => r.month && r.month < endMonth && hasVal(r.mari_uber_fees))
                     .sort((a, b) => a.month.localeCompare(b.month)).slice(-3);
  let all = 0, only = 0;
  for (const r of months) { all += toNum(r.mari_uber_fees); only += toNum(r.mari_uber_only); }
  return all ? Math.min(1, only / all) : 0.89;
}

function uberDirectActual(venue, sIso, eIso) {
  if (venue !== 'mari') return null;
  const rows = STATE.uberDirect || [];
  let min = null, max = null;
  for (const r of rows) {
    if (r.shop !== venue) continue;
    if (min === null || r.date < min) min = r.date;
    if (max === null || r.date > max) max = r.date;
  }
  if (min === null) return null;
  let fee = 0;
  for (const r of rows) {
    if (r.shop === venue && r.date >= sIso && r.date <= eIso) fee += toNum(r.fee_inc_gst);
  }
  return { fee, covered: sIso >= min && eIso <= max };
}

function venueRevWindow(venue, sIso, eIso) {
  let rev = 0;
  for (const r of (STATE.histories[venue] || [])) {
    if (r.date >= sIso && r.date <= eIso) rev += toNum(r.revenue_ex_gst);
  }
  return rev;
}

function doorDashFromBooks(venue, sIso, eIso) {
  // DoorDash, recovered from the accounts. It has no feed of its own.
  //
  // WHY this function has to exist: xero_pull.py builds TWO Uber figures --
  // mari_uber_fees (all third-party delivery) and mari_uber_only (the UberEats
  // account alone) -- and its own comment says the difference is "DoorDash +
  // Uber Direct". venueDeliveryEst used to replace that whole difference with
  // dir.fee the moment the Uber Direct feed covered the window, which silently
  // dropped DoorDash: A$545.95 in May 2026 and A$624.47 in June. It reads ~0
  // from July, which is why nobody caught it -- DoorDash appears to have
  // stopped, so the bug went quiet on its own instead of being found.
  // Understating cost flatters the margin, the direction CLAUDE.md warns about.
  //
  // Basis: the books are ex-GST, the delivery line here is inc-GST (see
  // uberRateFallback), so the recovered figure is grossed back up by 1.1.
  // Apportioned by REVENUE, not by days: a week is not a flat seventh of a
  // month's trading.
  if (venue !== 'mari') return 0;
  const oh = STATE.xeroOH || [];
  if (!oh.length) return 0;
  let out = 0;
  for (const r of oh) {
    const m = r.month;
    if (!m || !hasVal(r.mari_uber_fees) || !hasVal(r.mari_uber_only)) continue;
    if (m < sIso.slice(0, 7) || m > eIso.slice(0, 7)) continue;
    // What the books say is NOT UberEats, less the Uber Direct we can see.
    let direct = 0;
    for (const d of (STATE.uberDirect || []))
      if (d.shop === 'mari' && d.date.slice(0, 7) === m) direct += toNum(d.fee_inc_gst) / 1.1;
    const dd = toNum(r.mari_uber_fees) - toNum(r.mari_uber_only) - direct;
    if (!(dd > 0)) continue;            // nothing left over: DoorDash is done
    let monthRev = 0, windowRev = 0;
    for (const h of (STATE.histories.mari || [])) {
      if (h.date.slice(0, 7) !== m) continue;
      const v = toNum(h.revenue_ex_gst);
      monthRev += v;
      if (h.date >= sIso && h.date <= eIso) windowRev += v;
    }
    if (monthRev > 0) out += dd * (windowRev / monthRev) * 1.1;
  }
  return out;
}

function venueDeliveryEst(venue, sIso, eIso, endIso) {
  const rev = venueRevWindow(venue, sIso, eIso);
  const dfr = deliveryFeesPct(venue, endIso);
  const dfEst = dfr ? rev * dfr.pct / 100 : 0;
  const _u = uberActual(venue, sIso, eIso);
  if (!_u) {
    let est = dfEst;
    if (venue === 'mari' && !est) { const rt = uberRateFallback('mari'); if (rt) est = rt * rev; }
    return { df: est, commission: 0, marketing: 0, direct: null, actual: false };
  }
  const dir = uberDirectActual(venue, sIso, eIso);
  const directActual = dir && dir.covered;
  // Uber Direct we can read per-day; DoorDash only exists in the books. Taking
  // dir.fee alone here is what dropped DoorDash -- see doorDashFromBooks.
  const doorDash = directActual ? doorDashFromBooks(venue, sIso, eIso) : 0;
  const nonUber = directActual ? dir.fee + doorDash
                               : dfEst * (1 - uberEatsShareOfDelivery(venue, endIso));
  // The feed's TAIL: days in the window the Uber pull has not reached yet. Their
  // revenue is already in the P&L, so leaving their fees out understates delivery
  // cost on every window ending today — and by a lot more if the pull is stuck.
  // Estimate just those days at the venue's own blended rate over the covered
  // part. An incomplete feed must never read as a complete one. (2026-08-09)
  let tail = 0;
  if (_u.coveredEnd && !_u.covered) {
    const covRev = venueRevWindow(venue, sIso, _u.coveredEnd);
    const tailRev = venueRevWindow(venue, isoDate(addDays(new Date(_u.coveredEnd), 1)), eIso);
    if (covRev > 0 && tailRev > 0) tail = (_u.commission + _u.marketing) / covRev * tailRev;
  }
  return { df: _u.commission + _u.marketing + tail + nonUber, commission: _u.commission,
           marketing: _u.marketing, direct: directActual ? dir.fee : null,
           doorDash: doorDash, actual: true, feedCovered: !!_u.covered, tailEst: tail };
}

function pnlWindow(day, venue = STATE.currentVenue) {
  const revAll = toNum(day.revenue_ex_gst);
  if (!revAll || !hasVal(day.wages_dollars)) return null;
  const daysAll = day.days_included || 1;
  const wdays = day.wage_days || daysAll;
  const rev = day.rev_wage_days ? toNum(day.rev_wage_days) : revAll;
  const endIso = winEnd(day);
  const a = actualCogs(venue, endIso);
  const estBase = day.cogs_wage_days && rev ? toNum(day.cogs_wage_days) / rev * 100 : toNum(day.cogs_pct);
  const cogsPct = a ? a.pct : estBase;
  const ohA = overheadsDailyRate(venue, endIso);
  const ohf = ohFactor(day, venue, wdays);
  const wages = toNum(day.wages_dollars);
  // Overheads = fixed OH + payroll tax/WC (both lumpy group costs, DOW-weighted).
  const oh = ((ohA ? ohA.rate : (OVERHEADS_WEEKLY[venue] || 0) / 7) + wageOncostDaily(venue, endIso)) * ohf;
  const fa = feesActualWindow(day, venue);
  // Delivery fees. Whole-month closed windows use booked/portal actuals (fa).
  // Otherwise venueDeliveryEst swaps in the live Uber Eats + Uber Direct daily
  // data per venue where it covers the window, and estimates the rest. Marketing
  // stays INSIDE df (Zak: no separate line). Group = sum of real venues when any
  // live data is present, else the blended trailing rate (older windows unchanged).
  const _win = String(day.date).includes(' — ') ? String(day.date).split(' — ') : [day.date, day.date];
  let df;
  if (fa) {
    df = fa.fees;
  } else if (venue === 'group') {
    const parts = REAL_VENUES.map(v => venueDeliveryEst(v, _win[0], _win[1], endIso));
    if (parts.some(p => p.actual)) df = parts.reduce((t, p) => t + p.df, 0);
    else { const dfr = deliveryFeesPct(venue, endIso); df = dfr ? rev * dfr.pct / 100 : 0; }
  } else {
    df = venueDeliveryEst(venue, _win[0], _win[1], endIso).df;
  }
  // Reclassify Mari driver wages from Wages -> Delivery (profit-neutral).
  const drv = driverDeliveryShift(day, venue);
  const wagesShown = wages - drv;
  df += drv;
  const cp = corpPayrollDaily(venue, endIso) * ohf;   // owners' salary, DOW-weighted
  // Interest + depreciation are OUT of the P&L (Zak/Olly BEP, 2026-07-22): both are
  // $0 in Olly's plan — depreciation isn't a cash cost we pay, and interest is a
  // balance-sheet item, not a day-to-day trading cost. So profit = operating profit.
  const fin = 0;
  const opProfit = rev - rev * cogsPct / 100 - wagesShown - oh - df - cp;
  const profit = opProfit - fin;
  return { rev, daysAll, wdays, a, cogsPct, ohA, oh, df, cp, fin, wages: wagesShown, driver: drv, opProfit, profit, partial: wdays < daysAll };
}

function overheadsDailyRate(venue, endIso) {
  const feed = STATE.xeroOH;
  if (!feed.length) return null;
  const endMonth = String(endIso || '').slice(0, 7);
  const months = feed.filter(r => r.month && r.month < endMonth && hasVal(r.stow_overheads)).sort((a, b) => a.month.localeCompare(b.month)).slice(-4);
  if (!months.length) return null;
  const val = r => venue === 'group'
    ? toNum(r.stow_overheads) + toNum(r.hg_overheads) + toNum(r.mari_overheads)
    : toNum(r[`${venue}_overheads`]);
  const daysIn = r => { const [y, m] = r.month.split('-').map(Number); return new Date(y, m, 0).getDate(); };
  const rates = months.map(r => val(r) / daysIn(r)).sort((a, b) => a - b);
  const n = rates.length;
  const median = n % 2 ? rates[(n - 1) / 2] : (rates[n / 2 - 1] + rates[n / 2]) / 2;
  return { rate: median, months: n };
}

function deliveryFeesPct(venue, endIso) {
  const feed = STATE.xeroOH;
  if (!feed.length) return null;
  const endMonth = String(endIso || '').slice(0, 7);
  const months = feed.filter(r => r.month && r.month < endMonth && (hasVal(r.mari_uber_fees) || hasVal(r.meu_fees)))
                     .sort((a, b) => a.month.localeCompare(b.month)).slice(-3);
  if (!months.length) return null;
  const monthSet = new Set(months.map(r => r.month));
  const revOf = v => (STATE.histories[v] || []).reduce((t, r) => monthSet.has(r.date.slice(0, 7)) ? t + toNum(r.revenue_ex_gst) : t, 0);
  let fees = 0, rev = 0;
  if (venue === 'mari') {
    fees = months.reduce((t, r) => t + toNum(r.mari_uber_fees), 0);
    rev = revOf('mari');
  } else if (venue === 'stow' || venue === 'hg') {
    fees = months.reduce((t, r) => t + toNum(r.meu_fees), 0);
    rev = revOf('stow') + revOf('hg');   // same % across both = revenue-share split
  } else {   // group
    fees = months.reduce((t, r) => t + toNum(r.mari_uber_fees) + toNum(r.meu_fees), 0);
    rev = revOf('mari') + revOf('stow') + revOf('hg');
  }
  if (!rev || !fees) return null;
  return { pct: fees / rev * 100, months: months.length };
}

function actualCogs(venue, endIso, nWeeks = 4) {
  const rowsAll = STATE.xeroCogs;
  if (!rowsAll.length) return null;
  const weeks = [...new Set(rowsAll.filter(r => r.week_ending <= endIso).map(r => r.week_ending))].sort().slice(-nWeeks);
  if (!weeks.length) return null;
  const vens = venue === 'group' ? REAL_VENUES : [venue];
  let purch = 0;
  for (const r of rowsAll) {
    if (weeks.includes(r.week_ending) && vens.includes(r.venue)) purch += toNum(r.actual_cogs_ex_gst);
  }
  // revenue over those same weeks, from the venue's daily history
  const hist = STATE.histories[venue] || [];
  let rev = 0;
  for (const we of weeks) {
    const end = new Date(we); const start = addDays(end, -6);
    const sIso = isoDate(start), eIso = we;
    for (const r of hist) if (r.date >= sIso && r.date <= eIso) rev += toNum(r.revenue_ex_gst);
  }
  if (!rev) return null;
  return { pct: purch / rev * 100, purchases: purch, revenue: rev, weeks: weeks.length, from: weeks[0], to: weeks[weeks.length - 1] };
}

function dowForecast(venue, dow) {
  STATE._fcst = STATE._fcst || {};
  if (!STATE._fcst[venue]) {
    const rows = STATE.histories[venue] || [];
    const by = [[], [], [], [], [], [], []];
    for (let i = rows.length - 1; i >= 0; i--) {
      const rev = toNum(rows[i].revenue_ex_gst);
      if (rev <= 0) continue;
      const d = new Date(rows[i].date).getDay();
      if (by[d].length < 8) by[d].push(rev);
      if (by.every(a => a.length >= 8)) break;
    }
    STATE._fcst[venue] = by.map(a => {
      if (!a.length) return 0;
      const s2 = [...a].sort((x, y) => x - y);
      return s2.length % 2 ? s2[(s2.length - 1) / 2] : (s2[s2.length / 2 - 1] + s2[s2.length / 2]) / 2;
    });
  }
  return STATE._fcst[venue][dow];
}

function venueForecast(venue, dow) {
  return venue === 'group'
    ? ['stow', 'hg', 'mari'].reduce((t, p) => t + (dowForecast(p, dow) || 0), 0)
    : (dowForecast(venue, dow) || 0);
}

function breakevenParts(venue, endIso) {
  const ohA = overheadsDailyRate(venue, endIso);
  // Fixed = real overheads + owner salary + payroll tax/WC. All lumpy group
  // costs that don't move with tonight's trade — the breakeven denominator.
  const fixedDaily = (ohA ? ohA.rate : (OVERHEADS_WEEKLY[venue] || 0) / 7)
                     + corpPayrollDaily(venue, endIso) + wageOncostDaily(venue, endIso);
  const a = actualCogs(venue, endIso);
  const dfr = deliveryFeesPct(venue, endIso);
  const wm = wageMedian12wk(STATE.histories[venue] || []);
  if (!a && wm === null) return null;
  const varPct = (a ? a.pct : 0) + (dfr ? dfr.pct : 0) + (wm || 0);
  if (varPct >= 95) return null;
  return { fixedDaily, varPct };
}

function actualCogsSplit(venue, endIso, nWeeks = 4) {
  const rowsAll = STATE.xeroCogs;
  if (!rowsAll.length) return null;
  const weeks = [...new Set(rowsAll.filter(r => r.week_ending <= endIso).map(r => r.week_ending))].sort().slice(-nWeeks);
  if (!weeks.length) return null;
  const vens = venue === 'group' ? REAL_VENUES : [venue];
  let food = 0, bev = 0;
  for (const r of rowsAll) if (weeks.includes(r.week_ending) && vens.includes(r.venue)) {
    food += toNum(r.food_ex_gst); bev += toNum(r.bev_ex_gst);
  }
  let fRev = 0, bRev = 0;
  for (const v of vens) {
    const hist = STATE.histories[v] || [];
    for (const we of weeks) {
      const sIso = isoDate(addDays(new Date(we), -6));
      for (const r of hist) if (r.date >= sIso && r.date <= we) {
        if (v === 'mari') fRev += toNum(r.revenue_ex_gst);
        else { fRev += toNum(r.food_ex_gst); bRev += toNum(r.bev_ex_gst); }
      }
    }
  }
  if (!fRev && !bRev) return null;
  return { food: fRev ? food / fRev * 100 : null, bev: bRev ? bev / bRev * 100 : null };
}

function uberSvcWindow(sIso, eIso) {
  const feed = STATE.uberFees || [];
  if (!feed.length) return null;
  const sundays = [];
  for (let d = new Date(sIso); isoDate(d) <= eIso; d = addDays(d, 1)) {
    if (d.getDay() === 0) sundays.push(isoDate(d));
  }
  if (!sundays.length) return null;
  const wk = {};
  for (const r of feed) if (r.venue === 'mari' && hasVal(r.service_fees_inc_gst)) wk[r.week_ending] = r;
  if (!sundays.every(su => wk[su])) return null;
  let svc = 0, mkt = 0;
  for (const su of sundays) { svc += toNum(wk[su].service_fees_inc_gst); mkt += toNum(wk[su].marketing_inc_gst); }
  return { svc: svc / 1.1, mkt: mkt / 1.1, weeks: sundays.length };
}

function wholeMonthEdges(sIso, eIso) {
  if (Number(sIso.slice(8)) > 3) return false;
  const eD = new Date(eIso);
  return new Date(eD.getFullYear(), eD.getMonth() + 1, 0).getDate() - eD.getDate() <= 2;
}

function feesActualWindow(day, venue = STATE.currentVenue) {
  const t = String((day && day.date) || '');
  if (!t.includes(' — ')) return null;
  const parts = t.split(' — ');
  const sIso = parts[0], eIso = parts[1];
  if (!wholeMonthEdges(sIso, eIso)) return null;
  const feed = Object.fromEntries(STATE.xeroOH.map(r => [r.month, r]));
  const curMonth = isoDate(sydneyToday()).slice(0, 7);
  const months = [];
  let cur = new Date(sIso.slice(0, 7) + '-01');
  while (isoDate(cur) <= eIso) {
    months.push(isoDate(cur).slice(0, 7));
    cur = new Date(cur.getFullYear(), cur.getMonth() + 1, 1);
  }
  if (!months.length || !months.every(m => feed[m] && m < curMonth)) return null;
  let mari = 0, meu = 0, uberOnly = 0;
  for (const m of months) {
    mari += toNum(feed[m].mari_uber_fees);
    uberOnly += toNum(feed[m].mari_uber_only);
    meu += toNum(feed[m].meu_fees);
  }
  // Portal override: swap the booked UberEats line for REAL portal service
  // fees (ex-marketing) when portal weeks cover the window. DoorDash +
  // Uber Direct stay from the books (mari_uber_fees - mari_uber_only).
  const u = uberSvcWindow(sIso, eIso);
  let portal = false;
  if (u && uberOnly) { mari = u.svc + (mari - uberOnly); portal = true; }
  const v = venue;
  let fees;
  if (v === 'mari') fees = mari;
  else if (v === 'group') fees = mari + meu;
  else {
    const revOf = vv => (STATE.histories[vv] || []).reduce((tt, r) => (r.date >= sIso && r.date <= eIso) ? tt + toNum(r.revenue_ex_gst) : tt, 0);
    const rs = revOf('stow'), rh = revOf('hg');
    fees = (rs + rh) ? meu * (v === 'stow' ? rs : rh) / (rs + rh) : 0;
  }
  return { fees, mari, meu, nMonths: months.length, portal, mkt: u ? u.mkt : null,
           uberEats: portal ? u.svc : uberOnly };
}

function closedMonthsSet() {
  const out = new Set();
  for (const r of STATE.xeroOH) if (r.month && Math.abs(toNum(r.stock_movement)) > 0.005) out.add(r.month);
  return out;
}

function actualProfitWindow(day) {
  const t = String((day && day.date) || '');
  if (!t.includes(' — ')) return null;
  const parts = t.split(' — ');
  const sIso = parts[0], eIso = parts[1];
  if (!wholeMonthEdges(sIso, eIso)) return null;
  const months = [];
  let cur = new Date(sIso.slice(0, 7) + '-01');
  while (isoDate(cur) <= eIso) {
    months.push(isoDate(cur).slice(0, 7));
    cur = new Date(cur.getFullYear(), cur.getMonth() + 1, 1);
  }
  const closed = closedMonthsSet();
  const feed = Object.fromEntries(STATE.xeroOH.map(r => [r.month, r]));
  if (!months.length || !months.every(m => closed.has(m) && feed[m])) return null;
  const v = STATE.currentVenue;
  const rev = toNum(day.revenue_ex_gst);
  if (!rev) return null;
  const purchV = { stow: 0, hg: 0, mari: 0 };
  for (const r of STATE.xeroCogs) {
    if (r.week_ending >= sIso && r.week_ending <= eIso && purchV[r.venue] !== undefined) {
      purchV[r.venue] += toNum(r.actual_cogs_ex_gst);
    }
  }
  const purchTot = purchV.stow + purchV.hg + purchV.mari;
  const cosShare = v === 'group' ? 1 : (purchTot ? purchV[v] / purchTot : 0);
  if (v !== 'group' && !cosShare) return null;
  const revOf = vv => (STATE.histories[vv] || []).reduce((tt, r) => (r.date >= sIso && r.date <= eIso) ? tt + toNum(r.revenue_ex_gst) : tt, 0);
  const meuShare = (v === 'stow' || v === 'hg') ? (() => {
    const rs = revOf('stow'), rh = revOf('hg');
    return (rs + rh) ? (v === 'stow' ? rs : rh) / (rs + rh) : 0;
  })() : 1;
  // Skip months without booked payroll/COS (e.g. Uber-fee-only backfill rows) —
  // those aren't real closed months, so 'actual' profit must not read them as zeros.
  if (!months.every(m => feed[m] && hasVal(feed[m].group_payroll))) return null;
  let cos = 0, wages = 0, oh = 0, df = 0, fin = 0;
  for (const m of months) {
    const r = feed[m];
    cos += toNum(r.group_cos_ex_misc) * cosShare;
    wages += toNum(r.group_payroll) * (PLAN_WAGE_SHARE[v] || 1);
    oh += v === 'group'
      ? toNum(r.stow_overheads) + toNum(r.hg_overheads) + toNum(r.mari_overheads)
      : toNum(r[v + '_overheads']);
    df += v === 'mari' ? toNum(r.mari_uber_fees)
        : v === 'group' ? toNum(r.mari_uber_fees) + toNum(r.meu_fees)
        : toNum(r.meu_fees) * meuShare;
    // Interest + depreciation are OUT of the P&L (Olly BEP = $0 for both). Kept
    // consistent with pnlWindow so the 'actual' and 'expected' profits share one
    // definition (operating profit, no finance). group_finance stays in the feed
    // for reference but never hits profit.
    fin += 0;
  }
  // group_payroll bundles staff wages, owner salary, payroll tax and workers-
  // comp. Split it to match the operational card and Zak's rule, with NO
  // estimation: staff wages are the ACTUAL Deputy figure for these months; what
  // is left (owners + payroll tax + WC — all lumpy actuals) moves to overheads.
  // PROFIT IS UNCHANGED — wages + oh are preserved to the cent; only the label
  // moves. Falls back to a no-op if histories are absent.
  const vens = v === 'group' ? REAL_VENUES : [v];
  let staffWages = 0, driverWages = 0;
  for (const vv of vens) for (const r of (STATE.histories[vv] || [])) {
    if (r.date >= sIso && r.date <= eIso) {
      staffWages += toNum(r.wages_dollars) + toNum(r.leave_dollars);
      if (vv === 'mari') driverWages += toNum(r.wages_driver_dollars);
    }
  }
  if (staffWages > 0 && staffWages <= wages) { oh += (wages - staffWages); wages = staffWages; }
  // Mari drivers are a delivery cost, not a wage (profit-neutral reclassification).
  if ((v === 'mari' || v === 'group') && driverWages > 0 && driverWages <= wages) { df += driverWages; wages -= driverWages; }
  const profit = rev - cos - wages - oh - df - fin;
  return { profit, cos, wages, oh, df, fin, rev, nMonths: months.length };
}

// Mari's delivery drivers are a DELIVERY cost, not a general wage (Zak, 2026-07-26):
// the 'delivery' number = Uber commission + Uber Direct + driver-team wages. We move
// the driver $ OUT of Wages and INTO Delivery, profit-neutrally (the total is
// identical; only the label moves). Only Mari has drivers, so 'group' inherits it.
// Gated on wages_dollars being present, since driver is a subset of that figure.
/* Internal split of the delivery cost for the card breakdown: Uber Eats
   (commission + marketing), Uber Direct, and our own driver team (Mari). ME&U +
   Doshii covers stow/hg. Built to sum EXACTLY to the delivery df used in the P&L
   (platform fees + driver), so the breakdown reconciles to the headline number. */
function deliveryBreakdown(day, venue) {
  const rev = toNum(day.revenue_ex_gst);
  const drv = driverDeliveryShift(day, venue);
  const _win = String(day.date).includes(' \u2014 ') ? String(day.date).split(' \u2014 ') : [day.date, day.date];
  const end = _win[1];
  const fa = feesActualWindow(day, venue);
  let platform = 0, uberEats = 0, uberDirect = 0, marketing = 0, meu = 0, actual = false, mktExcluded = false;
  if (fa) {
    actual = true; marketing = fa.mkt || 0; mktExcluded = fa.portal && marketing > 0;
    if (venue === 'mari') { platform = fa.fees; uberEats = fa.uberEats || 0; uberDirect = Math.max(0, platform - uberEats); }
    else if (venue === 'group') { platform = fa.fees; uberEats = fa.uberEats || 0; uberDirect = Math.max(0, fa.mari - uberEats); meu = fa.meu; }
    else { platform = fa.fees; meu = fa.fees; }
  } else if (venue === 'mari') {
    const p = venueDeliveryEst('mari', _win[0], _win[1], end);
    platform = p.df; actual = p.actual; marketing = p.marketing;
    uberEats = p.commission + p.marketing;
    uberDirect = p.direct !== null ? p.direct : Math.max(0, p.df - p.commission - p.marketing);
  } else if (venue === 'group') {
    const parts = REAL_VENUES.map(v => venueDeliveryEst(v, _win[0], _win[1], end));
    platform = parts.some(p => p.actual) ? parts.reduce((t, p) => t + p.df, 0)
      : (() => { const dfr = deliveryFeesPct(venue, end); return dfr ? rev * dfr.pct / 100 : 0; })();
    const pm = venueDeliveryEst('mari', _win[0], _win[1], end);
    actual = pm.actual; marketing = pm.marketing;
    uberEats = pm.commission + pm.marketing;
    uberDirect = pm.direct !== null ? pm.direct : Math.max(0, pm.df - pm.commission - pm.marketing);
    meu = ['stow', 'hg'].reduce((t, v) => t + venueDeliveryEst(v, _win[0], _win[1], end).df, 0);
  } else {
    const p = venueDeliveryEst(venue, _win[0], _win[1], end);
    platform = p.df; meu = p.df;
  }
  return { rev, uberEats, uberDirect, marketing, mktExcluded, meu, driver: drv,
           platform, total: platform + drv, actual, venue };
}

function driverDeliveryShift(day, venue) {
  if (venue !== 'mari' && venue !== 'group') return 0;
  if (!hasVal(day.wages_dollars)) return 0;
  return toNum(day.wages_driver_dollars);
}

function toNum(x) { const n = parseFloat(x); return isFinite(n) ? n : 0; }

function hasVal(x) { return x != null && x !== '' && isFinite(parseFloat(x)); }

function grossRev(day) { return toNum(day.revenue_ex_gst) + toNum(day.eatclub_giveaway_ex_gst); }

function isoDate(d) { return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0'); }

function sydneyToday() { const d = new Date(); d.setHours(0, 0, 0, 0); return d; }

function addDays(d, n) { const c = new Date(d); c.setDate(c.getDate() + n); return c; }

function quarterStart(d) { const q = Math.floor(d.getMonth() / 3); return new Date(d.getFullYear(), q * 3, 1); }

function monthStart(d) { return new Date(d.getFullYear(), d.getMonth(), 1); }

function weekStart(d) { const day = d.getDay(); const offset = day === 0 ? -6 : 1 - day; return addDays(d, offset); }

function periodIsOpen() {
  const tf = STATE.currentTimeframe;
  if (tf === 'day') return true;                       // daily is always KPI-only
  const today = sydneyToday();
  const rows = STATE.histories[STATE.currentVenue] || STATE.histories.stow || [];
  const anchor = STATE.currentDay ? new Date(STATE.currentDay)
    : (rows.length ? new Date(rows[rows.length - 1].date) : today);
  let end;
  if (tf === 'week') end = addDays(weekStart(anchor), 6);
  else if (tf === 'month') end = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0);
  else if (tf === 'quarter') { const q = quarterStart(anchor); end = new Date(q.getFullYear(), q.getMonth() + 3, 0); }
  else if (tf === 'thisfy') { const fy = today.getMonth() >= 6 ? today.getFullYear() : today.getFullYear() - 1; end = new Date(fy + 1, 5, 30); }
  else if (tf === 'range') end = STATE.rangeEnd ? new Date(STATE.rangeEnd) : today;
  else return false;   // lastweek / lastmonth / lastquarter / lastfy / last12 / all → complete
  return end >= today;
}

var SUM_FIELDS = ['revenue_ex_gst', 'cogs_dollars', 'wages_dollars', 'delivery_dollars', 'gp_dollars',
  'food_ex_gst', 'bev_ex_gst', 'food_cogs', 'bev_cogs', 'wages_kitchen_dollars', 'wages_foh_dollars',
  'wages_driver_dollars', 'eatclub_giveaway_ex_gst', 'eatclub_covers'];

function rowsForTimeframe(rows, timeframe, anchorDay) {
  const anchor = new Date(anchorDay);
  if (timeframe === 'day') return rows.filter(r => r.date === anchorDay);
  if (timeframe === 'range') {
    if (!STATE.rangeStart || !STATE.rangeEnd) return [];
    return rows.filter(r => r.date >= STATE.rangeStart && r.date <= STATE.rangeEnd);
  }
  let start, endIso = anchorDay;
  if (timeframe === 'week')    start = weekStart(anchor);
  if (timeframe === 'month')   start = monthStart(anchor);
  if (timeframe === 'quarter') start = quarterStart(anchor);
  // Completed windows — computed off today, independent of the data anchor.
  const today = sydneyToday();
  if (timeframe === 'lastweek') {
    const thisWk = weekStart(today);
    start = addDays(thisWk, -7); endIso = isoDate(addDays(thisWk, -1));
  }
  if (timeframe === 'lastmonth') {
    const thisMo = monthStart(today);
    start = new Date(thisMo.getFullYear(), thisMo.getMonth() - 1, 1);
    endIso = isoDate(addDays(thisMo, -1));
  }
  if (timeframe === 'lastquarter') {
    const thisQ = quarterStart(today);
    start = new Date(thisQ.getFullYear(), thisQ.getMonth() - 3, 1);
    endIso = isoDate(addDays(thisQ, -1));
  }
  // AU financial year: 1 Jul - 30 Jun
  const fyStartYear = today.getMonth() >= 6 ? today.getFullYear() : today.getFullYear() - 1;
  if (timeframe === 'thisfy') {
    start = new Date(fyStartYear, 6, 1);
  }
  if (timeframe === 'lastfy') {
    start = new Date(fyStartYear - 1, 6, 1);
    endIso = isoDate(new Date(fyStartYear, 5, 30));
  }
  if (timeframe === 'last12') {
    start = addDays(today, -365);
  }
  if (timeframe === 'all') {
    return rows;
  }
  const startIso = isoDate(start);
  return rows.filter(r => r.date >= startIso && r.date <= endIso);
}

function rollup(rows) {
  if (!rows.length) return null;
  if (rows.length === 1) return rows[0];
  const sums = {};
  for (const f of SUM_FIELDS) sums[f] = 0;
  const present = {};
  let n = 0, wageDays = 0, revW = 0, cogsW = 0;
  const dowCounts = [0, 0, 0, 0, 0, 0, 0];
  for (const r of rows) {
    if (!r.revenue_ex_gst) continue;
    for (const f of SUM_FIELDS) {
      if (hasVal(r[f])) { sums[f] += toNum(r[f]); present[f] = true; }
    }
    if (hasVal(r.wages_dollars)) {
      wageDays++; revW += toNum(r.revenue_ex_gst); cogsW += toNum(r.cogs_dollars);
      dowCounts[new Date(r.date).getDay()]++;
    }
    n++;
  }
  if (n === 0) return null;
  const rev = sums.revenue_ex_gst;
  const out = {
    date: rows[0].date + ' — ' + rows[rows.length - 1].date,
    days_included: n,
    wage_days: wageDays, rev_wage_days: revW, cogs_wage_days: cogsW, dow_counts: dowCounts,
    revenue_ex_gst: sums.revenue_ex_gst,
    cogs_dollars: sums.cogs_dollars, cogs_pct: rev ? sums.cogs_dollars / rev * 100 : 0,
    wages_dollars: wageDays ? sums.wages_dollars : '',
    wages_pct: wageDays && revW ? sums.wages_dollars / revW * 100 : '',
    wages_driver_dollars: wageDays ? sums.wages_driver_dollars : '',
    delivery_dollars: sums.delivery_dollars, delivery_pct: rev ? sums.delivery_dollars / rev * 100 : 0,
    gp_dollars: sums.gp_dollars, gp_pct: rev ? sums.gp_dollars / rev * 100 : 0,
    eatclub_giveaway_ex_gst: sums.eatclub_giveaway_ex_gst, eatclub_covers: sums.eatclub_covers,
    cogs_alert: 'unknown', wages_alert: 'unknown', delivery_alert: 'unknown', gp_alert: 'unknown',
  };
  // Split lanes: only emit when at least one row in range carried the field,
  // so the pre-split history doesn't render misleading zeros.
  if (present.food_ex_gst) {
    out.food_ex_gst = sums.food_ex_gst;
    out.food_cogs = sums.food_cogs;
    out.food_cogs_pct = sums.food_ex_gst ? sums.food_cogs / sums.food_ex_gst * 100 : 0;
    out.food_gp_pct = sums.food_ex_gst ? (sums.food_ex_gst - sums.food_cogs) / sums.food_ex_gst * 100 : 0;
  }
  if (present.bev_ex_gst) {
    out.bev_ex_gst = sums.bev_ex_gst;
    out.bev_cogs = sums.bev_cogs;
    out.bev_cogs_pct = sums.bev_ex_gst ? sums.bev_cogs / sums.bev_ex_gst * 100 : 0;
    out.bev_gp_pct = sums.bev_ex_gst ? (sums.bev_ex_gst - sums.bev_cogs) / sums.bev_ex_gst * 100 : 0;
  }
  if (present.wages_kitchen_dollars) {
    out.wages_kitchen_dollars = sums.wages_kitchen_dollars;
    out.wages_kitchen_pct = sums.food_ex_gst ? sums.wages_kitchen_dollars / sums.food_ex_gst * 100 : '';
  }
  if (present.wages_foh_dollars) {
    out.wages_foh_dollars = sums.wages_foh_dollars;
    out.wages_foh_pct = sums.bev_ex_gst ? sums.wages_foh_dollars / sums.bev_ex_gst * 100 : '';
  }
  return out;
}


/* ---- Average spend (SPH) — reads STATE.sph (data/sph_daily.csv), the same
   per-day per-venue file the weekly Monday report uses. Definition matches
   build_weekly_report.sph_for_week exactly: day-weighted sum(Sales)/sum(Txns),
   Sales is INCL GST (spend-per-head convention). Pure; no DOM. */
var SPH_VENUE_MAP = { Stowaway: 'stow', 'Stowaway Bar': 'stow', HarryGatos: 'hg',
  'Harry Gatos': 'hg', Marilynas: 'mari', 'Marilynas-Uber': 'mari', "Marilyna's": 'mari',
  Marilyna: 'mari', Mari: 'mari' };

function sphVenueCode(v) {
  return SPH_VENUE_MAP[v] || String(v || '').toLowerCase().replace(/[^a-z]/g, '');
}

function sphWindowIso(day) {
  const t = String((day && day.date) || '');
  if (t.includes(' — ')) { const p = t.split(' — '); return [p[0], p[1]]; }
  return [t, t];
}

/* Aggregate SPH for a venue over [sIso,eIso]. Group = sum of the real venues
   PRESENT in the file (distinct tills — no double count as long as the file
   doesn't carry both a combined and a component row for the same till). */
function sphAggregate(venue, sIso, eIso) {
  const rows = STATE.sph || [];
  if (!rows.length) return null;
  const want = venue === 'group' ? ['stow', 'hg', 'mari'] : [venue];
  let sales = 0, txns = 0, guests = 0, guestSales = 0; const days = {};
  for (const r of rows) {
    const v = sphVenueCode(r.Venue);
    if (want.indexOf(v) < 0) continue;
    const d = r.Date;
    if (!(d >= sIso && d <= eIso)) continue;
    sales += toNum(r.Sales); txns += toNum(r.Transactions); days[d] = 1;
    const g = toNum(r.Guests);
    if (g) { guests += g; guestSales += toNum(r.Sales); }   // only rows that logged guests
  }
  if (!txns) return null;
  const vset = {};
  for (const r of rows) { const v = sphVenueCode(r.Venue); if (want.indexOf(v) >= 0 && r.Date >= sIso && r.Date <= eIso && toNum(r.Transactions)) vset[v] = 1; }
  return { sales, txns, guests, perTxn: sales / txns,
           perGuest: (guests && guests >= txns * 0.5) ? guestSales / guests : null,  /* only when guests logged on most sales (HG dine-in); sparse-guest venues (bar/pizza) -> no per-guest */ days: Object.keys(days).length,
           venues: Object.keys(vset).sort().join(',') };
}

function avgSpendWindow(venue, day) {
  const w = sphWindowIso(day);
  return sphAggregate(venue, w[0], w[1]);
}

/* YoY on spend per transaction (default) or per guest: same window, -364 days. */
function avgSpendYoY(venue, day, metric) {
  metric = metric || "perTxn";
  const w = sphWindowIso(day);
  const cur = sphAggregate(venue, w[0], w[1]);
  if (!cur || !cur[metric]) return null;
  const ps = isoDate(addDays(new Date(w[0]), -364));
  const pe = isoDate(addDays(new Date(w[1]), -364));
  const prev = sphAggregate(venue, ps, pe);
  if (!prev || !prev[metric]) return null;
  // Guard: a venue only recently started tracking SPH (Stow/HG from 2026) — if
  // last year's window is missing a venue that's in this year's, the comparison
  // is apples-to-oranges (e.g. group = all 3 now vs Mari-only a year ago). Skip.
  if (cur.venues !== prev.venues) return null;
  return (cur[metric] - prev[metric]) / prev[metric] * 100;
}
