"""Quantify (not fix) the Marilyna's pizza-ingredient recipe gap."""
import csv, json, re
from collections import defaultdict

B = "/Users/Shared/ClaudeShared/par-build"
rows = list(csv.DictReader(open(f"{B}/data/products_weekly.csv")))
weeks = sorted(set(r["week_ending"] for r in rows))[-13:]

rep = json.load(open(f"{B}/data/par_unattributed_marilynas.json"))
needs = rep.get("needs_recipe", [])

def f(x):
    try: return float(x)
    except (TypeError, ValueError): return 0.0

# volume + revenue for the needs_recipe lines
names = {r.get("product") or r.get("product_name") for r in needs}
vol = defaultdict(float); rev = defaultdict(float)
for r in rows:
    if r["venue"] == "mari" and r["week_ending"] in weeks and r["product_name"] in names:
        vol[r["product_name"]] += f(r["qty"]); rev[r["product_name"]] += f(r["sales_ex_gst"])

tot_q = sum(vol.values()); tot_r = sum(rev.values())
top = sorted(vol.items(), key=lambda kv: -rev[kv[0]])[:25]

# Stowaway pars that are plainly pizza inputs and carry no modelled demand
stow = json.load(open(f"{B}/data/par_recommendations_stowaway.json"))
PIZZA = re.compile(r"pizza|mozzarella|pepperoni|dough|flour|tomato|calabrese|"
                   r"prosciutto|ham |salami|cheese|base|bocconcini|olive|"
                   r"chorizo|pineapple|box", re.I)
blind = []
for r in stow["skus"]:
    if not PIZZA.search(r["product"]):
        continue
    d = r["drivers"]
    demand = d["pour_wk"] + d["recipe_wk"]
    live = r.get("current_par")
    if demand < 0.05 and live:
        blind.append((live, r["product"], r["rec_par"]))
blind.sort(reverse=True)

L = []
A = L.append
A("# Marilyna's — the pizza-ingredient recipe gap\n")
A("_Generated by `ops/gen_mari_gap.py`. Quantified only; no recipes invented._\n")
A("## What this is\n")
A("Marilyna's has no till of its own — its sales are an attributed slice of the")
A("Stowaway till, and its stock is **Stowaway's**, ordered against Stowaway par")
A("SKUs. Its packaged drinks now flow through to those pars automatically.\n")
A("Its **pizzas do not**, because a pizza is a finished good: it consumes flour,")
A("mozzarella, pepperoni, bases and boxes through a RECIPE. Without recipes that")
A("consumption is invisible, so the pars for those inputs carry no demand signal")
A("at all — they are set by hand and cannot self-correct.\n")
A(f"## The size of it\n")
A(f"- **{len(needs)} Marilyna's POS lines** sell with no recipe")
A(f"- **{tot_q/len(weeks):,.0f} units/week** ({tot_q:,.0f} over {len(weeks)} weeks)")
A(f"- **${tot_r:,.0f} ex-GST** of sales over {len(weeks)} weeks\n")
A("## What this means for the pars today\n")
A("Checked honestly, only **one** pizza input currently carries a live par:\n")
A("| live par | SKU | model says |")
A("|---:|---|---:|")
for live, name, rec in blind[:25]:
    A(f"| {live} | {name} | {rec} |")
A("")
A("Every other pizza input (mozzarella, pizza flour, dough, tomato sauce, the")
A("boxes) sits at par 0 — i.e. Marilyna's stock is currently managed OUTSIDE the")
A("par system entirely, by hand.\n")
A("So the recipe gap is not, today, causing bad pars on those items: there are no")
A("pars on those items to be bad. What it does mean is that the model **cannot be")
A("switched on** for Marilyna's stock until the recipes exist — and that the one")
A("input that IS parred (pepperoni) is running with no demand signal behind it.\n")
A("## Where the volume is — the recipe work queue\n")
A("Top 25 Marilyna's products by revenue that need a recipe:\n")
A("| /wk | 13wk ex-GST | product |")
A("|---:|---:|---|")
for name, q in top:
    A(f"| {q/len(weeks):.1f} | ${rev[name]:,.0f} | {name} |")
A("")
A("## Consequence\n")
A("Until these recipes exist, Marilyna's is a large, invisible draw on Stowaway")
A("stock. Pizza-input pars will keep needing manual correction, and the shrinkage")
A("engine will misread the gap as loss rather than unmodelled consumption — the")
A("one place a shrinkage number should be treated with suspicion.\n")

open(f"{B}/data/_par_review/marilynas_recipe_gap.md", "w").write("\n".join(L))
print(f"wrote marilynas_recipe_gap.md | {len(needs)} lines, {tot_q/len(weeks):.0f}/wk, ${tot_r:,.0f}")
print(f"pizza-input pars ordered blind: {len(blind)}")
for live, name, rec in blind[:10]:
    print(f"   live {live:>6}  {name}")
